# Generated by Django 5.2.8 on 2025-12-02 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное мероприятие')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram username')),
                ('first_and_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия')),
                ('about', models.TextField(blank=True, max_length=200, null=True, verbose_name='О себе (стек, опыт, интересы)')),
                ('networking_profile_filled', models.BooleanField(default=False, verbose_name='Анкета нетворкинга заполнена')),
                ('role', models.CharField(choices=[('guest', 'Гость'), ('speaker', 'Докладчик'), ('organizer', 'Организатор')], default='guest', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(blank=True, to='tg_bot.event', verbose_name='Мероприятия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст вопроса')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ спикера')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано спикером')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Получен ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tg_bot.event')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_questions', to='tg_bot.user', verbose_name='Автор вопроса')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_questions', to='tg_bot.user', verbose_name='Докладчик')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='current_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_speaker_at', to='tg_bot.user', verbose_name='Текущий докладчик'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название доклада')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание доклада')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок выступления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='tg_bot.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.user', verbose_name='Докладчик')),
            ],
            options={
                'verbose_name': 'График выступлений',
                'verbose_name_plural': 'Графики выступлений',
                'ordering': ['event', 'order'],
                'unique_together': {('event', 'speaker', 'order')},
            },
        ),
        migrations.CreateModel(
            name='NetworkingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('about', models.TextField(max_length=200, verbose_name='О себе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networking_profile', to='tg_bot.user')),
            ],
            options={
                'verbose_name': 'Профиль нетворкинга',
                'verbose_name_plural': 'Профили нетворкинга',
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('skipped', models.BooleanField(default=False, verbose_name='Пропущено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.event')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_matches', to='tg_bot.user')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_matches', to='tg_bot.user')),
            ],
            options={
                'verbose_name': 'История матчей',
                'verbose_name_plural': 'Истории матчей',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'initiator', 'target')},
            },
        ),
    ]
